- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.rst
- src/isal/igzip.py
- src/isal/isal_zlib.pyx
> Create a working igzip app.

- .travis.yml
> Simplify build environment

- CHANGELOG.rst
- setup.py
- src/isal/igzip.py
- src/isal/isal_zlib.pyx
- tests/test_gzip_compliance.py
- tests/test_isal.py
- tests/test_zlib_compliance.py
- tox.ini
> Add compliance tests

- CHANGELOG.rst
- docs/conf.py
- docs/igzip.rst
- docs/index.rst
- docs/isal_zlib.rst
- src/isal/igzip.py
- src/isal/isal_zlib.pyx
- tests/test_zlib_compliance.py
> Add API documentation

- .readthedocs.yml
- .travis.yml
- CHANGELOG.rst
- README.rst
- docs/conda-environment.yml
- setup.py
> Create documentation on readthedocs.

- .travis.yml
- CHANGELOG.rst
- setup.py
> Added python 3.9

- pyproject.toml
- setup.py
- src/isal/igzip.py
- tests/test_gzip_compliance.py
- tests/test_zlib_compliance.py
- tox.ini
Unfortunately couldn't get Cython coverage to work :slightly_frowning_face: .
> Add some coverage improvements

- .github/release_checklist.md
- .github/workflows/ci.yml
- .gitmodules
- CHANGELOG.rst
- MANIFEST.in
- README.rst
- buildwheels.sh
- pyproject.toml
- setup.py
- src/isal/__init__.py
- src/isal/igzip.py
- tests/test_gzip_compliance.py
- tests/test_zlib_compliance.py
- tox.ini
> Release 0.3.0

- .github/workflows/ci.yml
- CHANGELOG.rst
- README.rst
- setup.py
> Add macos to ci.yml

- .github/workflows/ci.yml
> Rework static install and build not to use conda

- CHANGELOG.rst
- src/isal/igzip.py
- tests/test_gzip_compliance.py
- tests/test_igzip.py
> Patch CLI to not crash on non .gz filename

- .github/release_checklist.md
- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip.py
- tests/test_gzip_compliance.py
- tests/test_igzip.py
> Release 0.6.1

- .github/workflows/ci.yml
- CHANGELOG.rst
- README.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip.py
- src/isal/isal_zlib.pyx
- tests/test_gzip_compliance.py
- tests/test_isal.py
- tests/test_zlib_compliance.py
> Release 0.7.0

- CHANGELOG.rst
- benchmark.py
- setup.py
- src/isal/__init__.py
- src/isal/igzip.py
- src/isal/isal_zlib.pyi
- src/isal/isal_zlib.pyx
- tests/test_igzip.py
> Release 0.8.0

- .github/workflows/ci.yml
- CHANGELOG.rst
- src/isal/isal_zlib.pyx
- tests/test_isal.py
- tox.ini
> Add pypy to supported versions.

- .github/workflows/ci.yml
- CHANGELOG.rst
> Add aarch64 support

- .github/workflows/ci.yml
- setup.py
- tox.ini
> Make sure conda pypy installations should work.

- .github/workflows/ci.yml
- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/isal_zlib.pyx
- tests/test_isal.py
- tox.ini
> Release 0.9.0

- CHANGELOG.rst
- src/isal/igzip.py
- tests/test_igzip.py
> Add flags for output to the CLI

- src/isal/isal_zlib.pyx
> Make sure error is raised by cython in data_is_gzip function.

- CHANGELOG.rst
- src/isal/igzip_lib.pyx
- tests/test_igzip_lib.py
> Fix incorrect behavior of unused data on IgzipDecompressor

- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip_lib.pyx
- tests/test_igzip_lib.py
- tox.ini
> Release 0.11.1

- CHANGELOG.rst
- src/isal/igzip.py
- src/isal/igzip_lib.pyi
- src/isal/igzip_lib.pyx
- tests/test_igzip_lib.py
> Unused data

- .github/workflows/ci.yml
- setup.py
- src/isal/igzip_lib.pyx
- src/isal/isal_zlib.pyx
- tox.ini
> Improve wheel build times with cache. Fix compiler warnings.

- src/isal/igzip.py
- tests/test_igzip.py
> Make code compatible with python 3.11 onwards

- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- tests/test_zlib_compliance.py
> Include isa-l.h on windows as well

- tests/test_igzip.py
Fixes #112 
Not 100% yet, but remaining lines are very hard to get covered.
> Increase test coverage

- .github/workflows/ci.yml
- .gitmodules
- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- tests/test_compat.py
- tests/test_zlib_compliance.py
> Use a patched version of isa-l 2.30

- .github/workflows/ci.yml
- MANIFEST.in
- setup.py
> Various build and CI fixes

- .github/workflows/ci.yml
- CHANGELOG.rst
- README.rst
- setup.py
- tests/test_igzip.py
- tests/test_igzip_lib.py
- tests/test_zlib_compliance.py
> Re-enable pypy support

- .github/workflows/ci.yml
- CHANGELOG.rst
- README.rst
- setup.py
- src/isal/__init__.py
- tests/test_igzip.py
- tests/test_igzip_lib.py
- tests/test_zlib_compliance.py
> Release 1.0.1

- CHANGELOG.rst
- src/isal/igzip_libmodule.c
- src/isal/isal_shared.h
- src/isal/isal_zlibmodule.c
> Add GIL escape to checksums and compress/decompress

- CHANGELOG.rst
- src/isal/igzip_libmodule.c
- src/isal/isal_zlibmodule.c
- tests/test_compat.py
- tests/test_igzip_lib.py
> Fix bugs when setting zdict

- .github/workflows/ci.yml
- CHANGELOG.rst
- setup.py
- tox.ini
> Try to fix windows CI

- setup.py
> Simplify ISA-L static build

- .github/workflows/ci.yml
> Simplerwheeltest

- .github/workflows/ci.yml
> Better tests for aarch64

- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip.py
- tests/test_igzip.py
> Release 1.3.0

- CHANGELOG.rst
- src/isal/igzip.py
- src/isal/isal_zlibmodule.c
> Also allow buffer protocol objects into _GzipReader

- .github/workflows/ci.yml
- CHANGELOG.rst
- setup.py
> Update python versions

- CHANGELOG.rst
- src/isal/igzip.py
- src/isal/igzip_threaded.py
- tests/test_igzip.py
- tests/test_igzip_threaded.py
- tox.ini
> Fix errors related to unclosed files

- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip.py
- src/isal/igzip_threaded.py
- tests/test_igzip.py
- tests/test_igzip_threaded.py
- tox.ini
> Release 1.4.1

- CHANGELOG.rst
- benchmark_scripts/memory_leak_test.py
- setup.py
- src/isal/__init__.py
- src/isal/isal_zlibmodule.c
- tox.ini
> Release 1.5.1

- CHANGELOG.rst
- src/isal/igzip_threaded.py
- tests/test_igzip_threaded.py
Fix for #172
Awaiting if this also fixes the actual bug downstream. @marcelm can you verify?
> Fix a bug where a filehandle would remain unclosed

- CHANGELOG.rst
- src/isal/igzip_threaded.py
- tests/test_igzip_threaded.py
> Fix append mode bug

- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip_threaded.py
- tests/test_igzip_threaded.py
> Release 1.5.3

- .gitmodules
> Use latest isa-l

- .github/workflows/ci.yml
- src/isal/isal_zlibmodule.c
> Test on latest python 3.13

- .github/workflows/ci.yml
- .gitmodules
- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip.py
- src/isal/igzip_threaded.py
- src/isal/isal_zlibmodule.c
- tests/test_compat.py
- tests/test_gzip_compliance.py
- tests/test_igzip_threaded.py
- tests/test_zlib_compliance.py
> Release 1.6.0

- CHANGELOG.rst
- src/isal/igzip_threaded.py
- tests/test_igzip_threaded.py
> igzip_threaded.open no longer closes streams that are passed to it

- CHANGELOG.rst
- setup.py
- src/isal/__init__.py
- src/isal/igzip_threaded.py
- tests/test_igzip_threaded.py
> Release 1.6.1

- .github/workflows/ci.yml
> Fix MacOS dynamic build

- setup.py
gmake and nasm needs to be installed (pkg install gmake nasm)
> Fix setup.py for FreeBSD, NetBSD

- .gitmodules
- CHANGELOG.rst
> Use a patched version of ISA-L 2.31 for MacOS arm64

- .github/workflows/ci.yml
- README.rst
- docs/conf.py
- docs/index.rst
- requirements-docs.txt
> Add a development chapter

- .github/workflows/ci.yml
> Fix aarch64 build

- CHANGELOG.rst
- src/isal/igzip.py
- src/isal/isal_zlibmodule.c
> Simplify code in igzip.py

- .github/release_checklist.md
- .github/workflows/ci.yml
- .gitignore
- .gitmodules
- CHANGELOG.rst
- MANIFEST.in
- README.rst
- docs/conf.py
- docs/index.rst
- pyproject.toml
- requirements-docs.txt
- setup.py
- src/isal/__init__.py
- src/isal/_version.pyi
- src/isal/igzip.py
- src/isal/isal_zlibmodule.c
> Release 1.7.0

- CHANGELOG.rst
- src/isal/igzip_threaded.py
- tests/test_igzip_threaded.py
> Fix flushing behaviour on threaded writing streams

- .github/release_checklist.md
- .github/workflows/ci.yml
- CHANGELOG.rst
- requirements-docs.txt
- setup.py
> Release 1.7.1

- docs/conf.py
> Remove unused theme option from doc configuration

- .gitmodules
- CHANGELOG.rst
> Update internal isa-l version to 2.31.1

- CHANGELOG.rst
- setup.py
> Enable building on GNU/Hurd platforms

- .github/workflows/ci.yml
- CHANGELOG.rst
- pyproject.toml
> Remove python 3.9 support and add 3.14 support
